# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_field', models.IntegerField(default=0)),
            ],
        ),
    ]
